### ISSUE TITLE
[question] Debugging "CMake failed"

### ISSUE THREAD

**Issue by senyai** [tttapa/py-build-cmake#40]
Hello!

I'm a first-time user. After running `TMP=tmp python -m build .`, I received the following error message:

```Command '['cmake', '-S', '/home/senyai/projects/videoreader/tmp/build-via-sdist-jj4bps4l/videoreader-0.0.1', '-B', '/home/senyai/projects/videoreader/tmp/build-via-sdist-jj4bps4l/videoreader-0.0.1/.py-build-cmake_cache/cp310-cp310-linux_x86_64', '-C', '/home/senyai/projects/videoreader/tmp/build-via-sdist-jj4bps4l/videoreader-0.0.1/.py-build-cmake_cache/cp310-cp310-linux_x86_64/py-build-cmake-preload.cmake', '-D', 'CMAKE_BUILD_TYPE:STRING=RelWithDebInfo']' returned non-zero exit status 1.```

I want to debug the CMake script to understand what is going wrong, but the tmp directory is cleaned up afterward. Is there a way to prevent the files from being deleted?

**Comment by tttapa** [comment]
By default, PyPA build will build your package from the sdist in a temporary directory. I'm not aware of any option to prevent it from removing that directory, but you can use build's `-w` flag to skip the sdist step and build in the source directory directly:

```sh
python -m build -w
```

**Comment by senyai** [comment]
Thanks. When I run `python -m build -w`, the project compiles successfully. However, I took a fresh look at my project and realized that I was missing some files.
_before_:
```toml
[tool.py-build-cmake.sdist]
include = ["CMakeLists.txt", "src/*", "include/*.*"]
```

_after_:
```toml
[tool.py-build-cmake.sdist]
include = ["CMakeLists.txt", "src/*", "include/videoreader/*.*"]
```
